/** @type {import('@docusaurus/plugin-content-docs/src/sidebars/types').Sidebars} */
module.exports = {
  someSidebar: [
    {
      type: 'category',
      label: '开始使用',
      items: [
        {
          type: 'autogenerated',
          dirName: 'getting-started',
        },
        {
          type: 'category',
          label: '指南',
          items: [
            {
              type: 'autogenerated',
              dirName: 'tutorial'
            }
          ]
        },
      ],
      className: 'category-as-header'
    },
    {
      type: 'category',
      label: '了解 BLUEPIPE',
      items: [
        {
          type: 'autogenerated',
          dirName:'concept'
        }
      ],
      className: 'category-as-header'
    },
    {
      type: 'category',
      label: '支持',
      className: 'category-as-header',
      items: [
        {
          type: 'autogenerated',
          dirName: 'support' // Generate sidebar slice from docs/api
        }
      ]
    }
  ]
};

