/** @type {import('@docusaurus/plugin-content-docs/src/sidebars/types').Sidebars} */
module.exports = {
  someSidebar: [
    {
      type: 'category',
      label: 'Getting Started',
      items: [
        {
          type: 'autogenerated',
          dirName: 'getting-started'
        }
      ],
      className: 'category-as-header'
    },
    {
      type: 'autogenerated',
      dirName: 'tutorial' // Generate sidebar slice from docs/api
    },
    {
      type: 'category',
      label: '连接器',
      className: 'category-as-header',
      items: [
        {
          type: 'autogenerated',
          dirName: 'connectors' // Generate sidebar slice from docs/api
        }
      ]
    },
    {
      type: 'category',
      label: '解决方案',
      className: 'category-as-header',
      items: [
        {
          type: 'autogenerated',
          dirName: 'examples' // Generate sidebar slice from docs/api
        }
      ]
    }
  ]
};

